# Generated by Django 3.2.25 on 2025-12-03 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='新闻标题')),
                ('content', models.TextField(verbose_name='新闻内容')),
                ('publish_time', models.DateTimeField(verbose_name='发布时间')),
                ('url', models.URLField(max_length=500, unique=True, verbose_name='新闻链接')),
                ('platform', models.CharField(choices=[('电商派Pro', '电商派Pro'), ('量子位', '量子位'), ('36kr', '36氪')], max_length=20, verbose_name='来源平台')),
                ('source_id', models.CharField(max_length=100, unique=True, verbose_name='平台内部ID')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='作者')),
                ('read_count', models.IntegerField(default=0, verbose_name='阅读量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('is_ad', models.BooleanField(default=False, verbose_name='是否为广告')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻列表',
                'ordering': ['-publish_time'],
            },
        ),
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_score', models.FloatField(verbose_name='情感得分')),
                ('sentiment_type', models.CharField(max_length=10, verbose_name='情感类型')),
                ('analysis_time', models.DateTimeField(auto_now_add=True, verbose_name='分析时间')),
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment', to='news_analysis.news', verbose_name='关联新闻')),
            ],
            options={
                'verbose_name': '情感分析结果',
                'verbose_name_plural': '情感分析结果列表',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news_analysis.news', verbose_name='关联新闻')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='news_analysis.comment', verbose_name='父评论')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='评论用户')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='news_analysis.comment', verbose_name='关联评论')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='点赞用户')),
            ],
            options={
                'verbose_name': '点赞',
                'verbose_name_plural': '点赞列表',
                'unique_together': {('user', 'comment')},
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50, verbose_name='关键词')),
                ('weight', models.FloatField(default=0.0, verbose_name='权重')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='news_analysis.news', verbose_name='关联新闻')),
            ],
            options={
                'verbose_name': '关键词',
                'verbose_name_plural': '关键词列表',
                'unique_together': {('news', 'keyword')},
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='news_analysis.news', verbose_name='收藏新闻')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL, verbose_name='收藏用户')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏列表',
                'unique_together': {('user', 'news')},
            },
        ),
    ]
