# Generated by Django 5.2.9 on 2025-12-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='platform',
            field=models.CharField(choices=[('量子位', '量子位'), ('36kr', '36氪')], max_length=20, verbose_name='来源平台'),
        ),
    ]
