# Generated by Django 5.2.9 on 2025-12-08 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_analysis', '0002_alter_news_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='is_ad',
        ),
    ]
